# Generated by Django 5.0.4 on 2024-04-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useraccount_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='role',
        ),
    ]
