# Generated by Django 5.0.3 on 2024-04-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_useraccount_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], default='patient', max_length=10),
        ),
    ]
