# Generated by Django 5.0.3 on 2024-04-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_drug_prescription'),
        ('api', '0009_alter_useraccount_user_type'),
    ]

    operations = [
    ]
