# Generated by Django 5.0.4 on 2024-04-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20240420_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='height_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='physician',
            field=models.CharField(default='Dr. Benjamin Park', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture_ref',
            field=models.CharField(default='default.jpg', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='weight_lb',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(max_length=10),
        ),
    ]
