# Generated by Django 5.0.4 on 2024-04-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_useraccount_dob_useraccount_height_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='DOB',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='height_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(default='(123) 456-7890', max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='physician',
            field=models.CharField(default='Dr. Benjamin Park', max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture_ref',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='weight_lb',
            field=models.IntegerField(default=0),
        ),
    ]
