# Generated by Django 5.0.4 on 2024-04-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_useraccount_physician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='physician',
            field=models.CharField(default='Dr. Benjamin Park', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture_ref',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
